# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'command.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.commandlist = QtWidgets.QListView(self.frame_4)
        self.commandlist.setObjectName("commandlist")
        self.verticalLayout_7.addWidget(self.commandlist)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.usageinput = QtWidgets.QLineEdit(self.groupBox_5)
        self.usageinput.setObjectName("usageinput")
        self.verticalLayout_5.addWidget(self.usageinput)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.commandinput = QtWidgets.QLineEdit(self.groupBox)
        self.commandinput.setObjectName("commandinput")
        self.verticalLayout_4.addWidget(self.commandinput)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.paraminput = QtWidgets.QLineEdit(self.groupBox_2)
        self.paraminput.setObjectName("paraminput")
        self.verticalLayout_3.addWidget(self.paraminput)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.moreinput = QtWidgets.QTextEdit(self.groupBox_3)
        self.moreinput.setObjectName("moreinput")
        self.verticalLayout_2.addWidget(self.moreinput)
        self.frame_2 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.savecommandbtn = QtWidgets.QPushButton(self.frame_2)
        self.savecommandbtn.setObjectName("savecommandbtn")
        self.horizontalLayout.addWidget(self.savecommandbtn)
        self.newcommandbtn = QtWidgets.QPushButton(self.frame_2)
        self.newcommandbtn.setObjectName("newcommandbtn")
        self.horizontalLayout.addWidget(self.newcommandbtn)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout_3.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.showresult = QtWidgets.QPlainTextEdit(self.groupBox_4)
        self.showresult.setAutoFillBackground(False)
        self.showresult.setReadOnly(True)
        self.showresult.setObjectName("showresult")
        self.verticalLayout_8.addWidget(self.showresult)
        self.execcommandbtn = QtWidgets.QPushButton(self.groupBox_4)
        self.execcommandbtn.setObjectName("execcommandbtn")
        self.verticalLayout_8.addWidget(self.execcommandbtn)
        self.horizontalLayout_2.addWidget(self.groupBox_4)
        self.horizontalLayout_3.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_5.setTitle(_translate("MainWindow", "指令用途"))
        self.groupBox.setTitle(_translate("MainWindow", "命令"))
        self.groupBox_2.setTitle(_translate("MainWindow", "參數"))
        self.groupBox_3.setTitle(_translate("MainWindow", "說明"))
        self.savecommandbtn.setText(_translate("MainWindow", "儲存命令"))
        self.newcommandbtn.setText(_translate("MainWindow", "新增命令"))
        self.groupBox_4.setTitle(_translate("MainWindow", "輸出結果"))
        self.execcommandbtn.setText(_translate("MainWindow", "執行命令"))
